services:
  ruby:
    build: . #ใช้ file ใน folder มา build auto
    command: ["sleep","infinity"]
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 8090:8080
      - 20000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
  apache:
    image: ubuntu/apache2
    ports:
      - "1234:80" 
volumes:
  jenkins_home:
