name: Docker Image CI

on:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: actions/checkout@v2
    - run: |
        test=$(date +%s) &&
        docker build . --file Dockerfile --tag jeepajeep/jekflix:$test &&
        docker push jeepajeep/jekflix:$test
    


  
      

      
